### ISSUE TITLE
Customer not assigned to manual orders - edge-case/issue

### ISSUE THREAD

**Issue by arraypress** [awesomemotive/easy-digital-downloads#9462] opened 2022-09-30 17:23 UTC
### Expected behavior
When I manually add an order and assign a new (or existing) customer, I expect the order to be completed with the customer assigned to the order.

### Actual behavior
The order is added but the customer is never assigned. It does not matter if it's a new or existing customer record.

I am unable to replicate this locally, but I have seen this issue on 3 separate client sites with almost nothing installed other than EDD 3.0. 

In some cases, they never had EDD 2.x prior either so it's not a backwards capability issue per-say. Regardless, it's breaking All Access passes and other things which require the customer ID (for obvious reasons).

I am going to investigate this further, but it was worth dropping an issue here because I am seeing this relatively often.

### Information (if a specific version is affected):
PHP Version: mixed (7.4 or 8.0).

EDD Version (or branch): 3.0.4

WordPress Version: latest

Any other relevant information:

**Comment by mihaijoldis** [comment] 2022-09-30 20:59
Hey @davidsherlock 
Just to confirm something here, the issue is that the Customer is not being assigned to the order or the User?
Also if you have access to the customer's database can you compare the structure of the edd_customers table against the one on your local?

**Comment by davidsherlock** [comment] 2022-09-30 21:31
I am going to take a look at the weekend, haven't had a chance as of yet to compare the tables and see what is going on.

The issue is with the orders not being assigned the customer.

**Comment by mihaijoldis** [comment] 2022-09-30 21:38
Can't replicate this locally :( check the customers and customer_meta tables and see if perhaps they are missing a field. Is it the same with just EDD on their sites or is there other extensions involved?

**Comment by davidsherlock** [comment] 2022-09-30 21:46
Yeah, I wasn't able to replicate it either tbh. But I have seen it a few times on completely different sites...

Here is the thing - no AJAX errors, no extensions enabled, etc..

It's been completely different client projects as well, so I am not sure what is going on. I will update this issue as I discover the potential cause of this.

**Comment by cklosowski** [comment] 2022-10-03 18:59
Ensure these users are all on EDD 3.0.4. This was fixed in EDD 3.0.4

**Comment by davidsherlock** [comment] 2022-10-03 20:42
I have actually discovered a bug with the All Access extension, but I am not able to add it to GitHub as I don't have access to those repos.

If you create an order and assign an access pass as a product, then save the payment the access pass will show as "invalid". I was able to replicate this on my local setup, as well as client sites so it's definitely an issue.

If I purchase the pass normally, everything works. It's just manually adding a payment that causes the issue.

**Comment by mihaijoldis** [comment] 2022-10-03 20:44
We have that fixed in the next release for All Access! It only sets to affect manual orders from the admin side.

**Comment by davidsherlock** [comment] 2022-10-03 20:48
Great, is there any ETA on that one? My client manually processes payments and then adds the passes so it's an important one to get fixed :)

Thanks for the update, @mihaijoldis!

**Comment by matt70** [comment] 2022-10-06 14:49
I had these problems after the update to 3.0, too. But with the newest updates for edd, all-access and manual-purchases it works fine, again.

**Comment by matt70** [comment] 2022-10-06 15:25
Do you have all-access 1.2.2?

**Comment by mihaijoldis** [comment] 2022-10-06 15:40
> @matt70 no, I'm not running the all-access plugin at all

Could you please send a ticket to our support team via our website and we will take a closer look at this. We would require some more information and we can't ask for that publicly here.

**Comment by cferdinandi** [comment] 2022-10-06 16:12
Yes, actually a few minutes _before_ you told me to, because I realized I should have gone through support first. I can resubmit, though.

**Comment by cklosowski** [comment] 2022-11-07 22:08
@robincornett I noticed that this is marked as being a resolution of an 'edge case' for manual order creation, is that correct? It's just changing how the existing tables are adjusted?

**Comment by cklosowski** [comment] 2022-11-10 05:45
Okay I'm going to remove this from the next milestone then. Thanks.

**Closed** 2023-11-06 21:34 UTC
Labels: type-bug, workflow-needs-testing, workflow-has-pr, workflow-needs-replication, workflow-pending-triage
