### ISSUE TITLE
System Info: Add listing of custom template files being used

### ISSUE THREAD

**Issue by shaynesanderson** [awesomemotive/easy-digital-downloads#8038] opened 2020-07-01 17:29 UTC
### Explain your enhancement (please be detailed)
Add listing of customized template files that have been added to theme directory to the system info file. This is currently in place for RCP 
### Justification or use case
Saves time and helps to quickly identify issues if custom code is in place.

Related: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4224

**Comment by cklosowski** [comment] 2022-08-24 09:50
This is now a duplicate of #7827. Closing this.

**Closed by cklosowski** 2022-08-24 09:50 UTC
