### ISSUE TITLE
Import fails with PHP 8

### ISSUE THREAD

**Issue by shaynesanderson** [awesomemotive/easy-digital-downloads#8839] opened 2021-08-31 17:04 UTC
### Expected behavior
When exporting data (Payment History) and importing, I expect the importer to bring in all data.

### Actual behavior
When using PHP 8, and clicking the "Import CSV" button, the import does not run.

### Steps to reproduce the behavior
1) Install EDD with PHP 8
2) Navigate to "Reports-->Export" and export Payment History
3) Navigate to "Tools-->Import/Export" and import Payment History
4) It appears to run quickly but never shows complete.

### Information (if a specific version is affected):
PHP Version: 8

EDD Version (or branch): 2.11.1

WordPress Version: 5.8

**Comment by robincornett** [comment] 2021-08-31 19:48
Note: this is a duplicate of #8453, which has been fixed for EDD 3.0. If @ashleyfae deems, we can implement the same changes in 2.11.x.

**Comment by shaynesanderson** [comment] 2021-08-31 19:52
My mistake! Thanks Robin.

**Comment by cklosowski** [comment] 2021-08-31 22:44
I would say if the changes made in #8453 are compatible all the way back to PHP 5.3 then we move forward. The 3.0 branches of EDD only run their unit tests all the way back to PHP 5.6, so we don't know yet if the change is compatible with these versions.

**Closed** 2022-01-10 13:41 UTC
Labels: type-bug
