### ISSUE TITLE
Chosen fields in admin don't recover from no results

### ISSUE THREAD

**Issue by Shelob9** [awesomemotive/easy-digital-downloads#4662] opened 2016-06-07 22:00 UTC
Happens in a few places, for example adding download to bundle.

I add a new download, type in the wrong thing, often times -- not consistently -- I have no way of starting over, have to delete the field and restart.

https://www.dropbox.com/s/z6zs5rbzg728fys/edd-select2.mov?dl=0

**Comment by pippinsplugins** [comment] 2016-06-07 22:30
I just ran into this today.

**Comment by Shelob9** [comment] 2016-06-08 02:28
Not sure if its just me, but I think it is worse on the payment admin screen. I'm struggling to figure out the exact behavior to reproduce this.

**Comment by sunnyratilal** [comment] 2016-06-30 19:01
Looks like the `input` field isn't clearing itself at times. I think it's a bug in Select2.

**Comment by chriscct7** [comment] 2016-07-05 00:21
We use chosen for that not Select2 don't we?

**Comment by cklosowski** [comment] 2016-07-05 00:22
Yea the point still stands at times though. Chosen doesn't always recover.

On Monday, July 4, 2016, Chris Christoff <notifications@github.com> wrote:

> We use chosen for that not Select2 don't we?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4662#issuecomment-230366046>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABU2LFMjdLOhmDj7U8l78FBq-j1vcmcQks5qSaODgaJpZM4IwZ5I>
> .
>


-- 
Sent from Gmail Mobile

**Comment by michaelbeil** [comment] 2016-08-17 19:33
I am seeing this today as well.

**Comment by michaelbeil** [comment] 2016-08-17 19:37
A customer is also having an issue with this in Manual Puchases: https://secure.helpscout.net/conversation/239907705/40288/?folderId=725711

**Comment by cklosowski** [comment] 2016-09-13 16:47
i can replicate it on the Download Bundle fields, but not on the `View Order Details` screen. I'll dig into Chosen and see what's going on there.

**Comment by pippinsplugins** [comment] 2016-09-13 16:55
I see it most often on `Manual Purchases.

**Comment by cklosowski** [comment] 2016-09-13 16:57
I think it has to do with our repeatable fields with the download selector. The Clone is doing something odd to them.

**Comment by SDavisMedia** [comment] 2016-09-14 18:19
I can only replicate when adding products to a bundle. Manual Purchases works fine but I can make the bundle test fail every time. 

Unfortunately, `issue/4662` is not changing the behavior for me.

**Comment by cklosowski** [comment] 2016-09-14 20:46
We're not getting consistant behavior between people, going to punt until we can dig further and avoid a hasty commit that affects other chosen fields.

**Comment by pippinsplugins** [comment] 2016-12-12 21:53
I have a customer reporting this same issue and I've had it happen in Manual Purchases on the easydigitaldownloads.com site.

**Comment by pippinsplugins** [comment] 2016-12-12 22:14
Quick way to replicate:

1. Activate Manual Purchases
2. Create new payment
3. Enter 4+ characters in the chosen search field to trigger an ajax search
4. Add the product
5. Add new row
6. Try and search for a different product by entering 4+ characters
7. Problem is now seen

**Comment by pippinsplugins** [comment] 2016-12-12 22:15
I've confirmed that issue/4662 does _not_ fix it.

**Comment by ghost1227** [comment] 2017-01-16 17:03
Well this is a bitch on so many levels...

**Comment by sunnyratilal** [comment] 2017-01-16 17:12
Yep I spent some time trying to figure this one and I kept getting stuck

**Comment by ghost1227** [comment] 2017-01-16 17:21
I can successfully unset the select box, but trying to reset the selected item fails. Somehow it's always presetting the field with the ajax return when a new one is created.

**Comment by ghost1227** [comment] 2017-01-16 20:33
Ok, I officially give up on this one. I keep getting halfway there, but can't quite fix it. I'll let smarter minds (or at least minds better with javascript) dig further.

**Comment by ghost1227** [comment] 2017-01-19 15:53
Been discussing this with @mindctrl and we've come to the conclusion that Chosen sucks.

**Comment by ghost1227** [comment] 2017-01-19 22:59
After more discussion and testing, I'm going to suggest something that I know is going to get me in trouble... I'm going to renew my suggestion from 2 years ago to replace Chosen with Select2 in EDD. We originally closed it because we were waiting for WP core to integrate it. Clearly, that's not going to happen any time soon. My reasons are as follows:

- The Chosen API is limited and poorly documented. @mindctrl said he had to dig into the code just to figure out how to do things, and even then they didn't work as expected.
- Chosen is still image-based. Select2 is not.
- Select2 is more feature-complete and much better documented.
- Whenever core _does_ integrate something, it's likely to be Select2, meaning less overhead for us to migrate in the future
- Select2 is designed to work with AJAX and large datasets, Chosen isn't.

I ran a quick test replacing this individual select box with one generated by Select2 and it resolved the issue this ticket presented. While performing that migration is a headache, it would allow us to get rid of a LOT of hackish javascript and optimize our admin js significantly.

**Comment by pippinsplugins** [comment] 2017-01-19 23:01
I am not opposed to re-considering select2 but not within the 2.7 release.

**Comment by ghost1227** [comment] 2017-01-19 23:02
Agreed, this doesn't belong in 2.7. However, I would propose re-opening the original ticket and tagging for 2.8, and bumping this to match.

**Comment by pippinsplugins** [comment] 2017-01-19 23:02
Re-tagging for 2.8 then.

**Comment by cklosowski** [comment] 2022-08-24 02:57
The updates in 3.0 seem to have resolved this.

**Closed by cklosowski** 2022-08-24 02:57 UTC
Labels: type-bug, component-administration, priority-high, workflow-has-pr
