### ISSUE TITLE
The price option assignment of download files (products) are not showing correctly on the WP-Admin Download page when using Variable Pricing and Product Type Bundle

### ISSUE THREAD

**Issue by napoleaowingert** [awesomemotive/easy-digital-downloads#9343] opened 2022-08-04 21:22 UTC
### Expected behavior
When I open an existing product on the WP-Admin Download page, which has a Product Type = Bundle, and I edit this product by changing the download files (products), I expect the price option assignments are correctly stored and displayed after refreshing the page.

### Actual behavior
The problem is that it is not correct after refreshing the page.

It shows "All" on the price option assignment for the newly created download file (product).

### Steps to reproduce the behavior
1) Create a new product with two price options (eg. Basic and Premium)
2) Change the product type to Bundle
3) Create a download file (product) and assign it to the Basic price option
4) Create another download file (product) and assign it to the Premium price option
5) Publish the product
6) Refresh the page if you are using Gutenberg
7) You will see everything is fine
8) Now create a new download file and assign it to the Basic price option
9) Remove the first download file which was also assigned to the Basic price option
10) Save the product
11) Refresh the page if you are using Gutenberg
12) See that you have a problem now

It might be that we don't need multiple price options, but I think that by using at least two price options can make this clearer.

### Information (if a specific version is affected):
PHP Version: latest

EDD Version (or branch): latest

WordPress Version: latest

Any other relevant information:

It looks like the values are stored as expected, but it is not showing them correctly.

I think this is related to the indexes of these post meta (because they don't match):
```_edd_bundled_products```
```_edd_bundled_products_conditions```

There are places like the ```get_variable_priced_bundled_downloads``` function (```EDD_Download``` class) that uses the ```array_values``` function so that the indexes are reset and they can match later, see: https://github.com/awesomemotive/easy-digital-downloads/blob/main/includes/class-edd-download.php#L572

But there are places like the ```edd_render_products_field``` function that are not using the same rule, see: https://github.com/awesomemotive/easy-digital-downloads/blob/main/includes/admin/downloads/metabox.php#L650 

_Edited to fix post meta key_

**Comment by cklosowski** [comment] 2022-08-04 22:26
@robincornett Could this be similar to something you saw in Content Restriction?

**Comment by napoleaowingert** [comment] 2022-08-10 14:13
Oh, I forgot to mention that this is a problem with EDD 3.0, just to be clear - I opened it as a Bug Report instead of Issue for EDD 3.0 because now EDD 3.0 is the latest version.

Are there any news @cklosowski?

**Comment by robincornett** [comment] 2022-08-10 14:49
I think the main cause of the problem might be in this line: https://github.com/awesomemotive/easy-digital-downloads/blob/main/includes/admin/downloads/metabox.php#L619

As I read the code, the `_edd_bundled_products` is intended to follow the same array key system as the variable pricing: that is, the count should start with `1`, not `0`. The `$index` variable is assigned to the `name` attribute for each input in the bundled product row, except for the actual product selection, so the two arrays can be keyed differently. On the initial load, the product is keyed to `1`, but on subsequent loads, it's not, so the arrays end up being keyed differently.

This has apparently been this way for a long time (the last time these inputs were touched was 2013 and 2016), so I don't know that it's _urgent_, but it's definitely wrong and should be fixed.

The `get_bundle_pricing_variations` method is also weird because it doesn't set the `$single` flag when it's getting the post meta, which is why the returned value has to be reset when it's used. But I would guess that's something we have to live with because it's been like that for so long.

**Comment by cklosowski** [comment] 2022-08-19 08:11
I've just confirmed this was a bug in EDD 2.11 as well, so it's not specific to 3.0 and therefore isn't a regression.

It is a confirmed bug however, since it existed previously I'm moving it to the next major milestone so we can clear some other higher priority issues in the 3.0 release.

**Comment by efmcyrill** [comment] 2022-09-07 13:47
@cklosowski will version 3.1 be the next one you plan to release? by when do you think you might be ready?

**Comment by cklosowski** [comment] 2022-09-07 14:27
@efmcyrill 3.1 is our next planned major milestone and is the version in active development. It's hard to say when it will be ready as there are a number of issues still to tackle but we're making great progress. Keep in mind there may be minor versions released in between if something arises that needs attention.

**Comment by napoleaowingert** [comment] 2022-09-13 14:06
@cklosowski This looks postponed once more, now to 3.2.

Currently, we simply can't change bundles because the price assignment doesn't work as per the main comment.

If it is possible to apply a simpler solution it would be great to allow everyone to edit bundles.

Making both meta values work with the same indexes and/or updating the database for this etc. can wait for a major fix I think

In case it is possible to just use the same array_values function call or something else as mentioned - there is already a place where this function is used to fix the indexes it seems.

Is there any easier solution? Thank you.

**Comment by efmcyrill** [comment] 2022-09-13 14:17
> @efmcyrill 3.1 is our next planned major milestone and is the version in active development. It's hard to say when it will be ready as there are a number of issues still to tackle but we're making great progress. Keep in mind there may be minor versions released in between if something arises that needs attention.

We think the whole Bundle Topics requires attention. Bundles are very valuable as they allow you to increase the average order value. This is a good function to have and we should use it more often.

**Comment by cklosowski** [comment] 2022-09-14 18:36
@efmcyrill We had a few issues that aren't going to make 3.1 as we need to make some decisions and replicate them still. I've put this back into the 3.1 milestone, so we can asses it and see what we can achieve in the time left before release.

**Closed** 2022-10-03 18:57 UTC
Labels: type-bug

**Comment by rottmann** [comment] 2023-10-27 14:12
The `edd_render_products_field` method is called with the $type `default` instead of empty.

Change line to:
```
function edd_render_products_field($post_id, $type = '')
{
    $download = new EDD_Download($post_id);

    if (empty($type) || 'default' === $type) {
```

let us edit the old data, but shows additional wrong upload fields for single products.
