### ISSUE TITLE
Bug: Deleting a customer & their orders turns into refunds 

### ISSUE THREAD

**Issue by morganhvidt** [awesomemotive/easy-digital-downloads#9420] opened 2022-09-07 10:54 UTC
### Expected behavior

I expect that deleting a customer and all their records removes the data completely, and their numbers are removed from reporting.

### Actual behavior

Deleted orders are turned into refunds, they only appear in new 'refunds' tab. The deleted orders are counted as refunds in the reports. This is big issue when cleaning up test orders etc. 

One a side note: what's the point of the new Refunds tab? I'm confused to why there are refunds in two locations.

### Steps to reproduce the behavior

1) Go to a customer page and delete them ( ✅ Are you sure you want to delete this customer? ✅ Delete all associated payments and records?)
2) Customer orders are deleted, they don't appear in the standard orders list.
3) Somehow duplicate versions of the orders appear in the "Refunds" tab. These fake 'refunds' also show up in reports?

Screenshot for reference below

### Information (if a specific version is affected):
PHP Version: 7.4

EDD Version (or branch): Version 3.0.4

WordPress Version: 6.0.2

<img width="1341" alt="Screen Shot 2022-09-07 at 12 32 57" src="https://user-images.githubusercontent.com/10958823/188860209-bb0231c3-411a-459d-abbb-97514cd5aca5.png">
 relevant information:

**Comment by robincornett** [comment] 2022-09-07 12:21
Replicated, and it's a little weird:
- The customer is deleted.
- The order is deleted.
- The order item is marked as refunded, but not deleted. At this point it appears to be an orphaned item.
- A refund order is created and linked to the customer who no longer exists.
- An order item is created for the refund order.

It looks like deleting a customer calls `edd_delete_purchase` for each of the customer's orders. I think the issue is in that function, because it calls `edd_undo_purchase`, which refunds the order, and then `edd_delete_order`. `edd_destroy_order` might be the correct choice there, and I don't think calling `edd_undo_purchase` is correct anymore.

**Comment by cklosowski** [comment] 2022-09-07 17:51
@robincornett I believe that is correct. When deleting a customer we should `destroy` the orders.

On the question about Refunds @morganhvidt.

In EDD 3.0 we have two types of 'Orders' that are recorded. Sales and Refunds.

This allows us to make it possible to properly report revenue attribution. In 2.x When you refunded a payment, it affected the revenue from the date that the item was originally purchased, which is incorrect from a store revenue perspective. It also resulted in the in-ability to properly refund only a specific item from an order that contained multiple times.

With 3.0 we record actual refund orders, so that we can do the following:
1. Provide a proper 'paper trail' of the history of an order, linking refunds with their original sale record.
2. Proper reporting of net and gross revenue.
3. Proper file access on orders with multiple products, as each independent item on an order can be refunded, while still providing access to file for non-refunded items.
4. Provide detailed and actionable reporting on how refunds affect your business by calculating things like average time to refund, refund % and total refunded revenue.

There are not 'refunds' in two locations.
A sale can have a status of 'refunded', however the actual refund itself has it's own transaction ID and row in the database in order to facilitate reporting and metrics.

**Closed** 2022-09-15 15:13 UTC
Labels: type-bug, component-customers, workflow-pending-triage
