### ISSUE TITLE
Add password reset form to [edd_login]

### ISSUE THREAD

**Issue by mindctrl** [awesomemotive/easy-digital-downloads#6546] opened 2018-05-07 22:11 UTC
### Explain your enhancement (please be detailed)
The _Lost Password_ link in `[edd_login]` links to WP core's `wp-login.php` version of the password reset form. It takes you to "another world". The reset link takes you through the `wp-login.php` experience too.

It would be nice to show a custom one in `[edd_login]`, to keep people on the front end of the site along with the familar design and branding, to make the whole experience cohesive.

### Justification or use case
EDD has several front-end forms to provide nicer experiences - registration, login, profile editor. `Lost Password` is missing from that fine list.

**Comment by pippinsplugins** [comment] 2018-05-08 00:44
Related: #3827

**Comment by robincornett** [comment] 2023-02-10 14:52
Closing as a duplicate of #3827 and we have done this in the login block with no plans to do it in the shortcode.

**Closed by robincornett** 2023-02-10 14:52 UTC
Labels: type-feature, component-forms
